
services:
  app:
    build: .
    container_name: app
    command: >
      bash -lc "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 3
      "
    expose:
      - "8001"
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      # - "443:443"   # SSL bo'lsa ochasiz
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-data:/app/staticfiles
      - media-data:/app/media
      # SSL fayllarini qo'ysangiz:
      # - /etc/letsencrypt/live/ittat.uz/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      # - /etc/letsencrypt/live/ittat.uz/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
