version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application
              --bind 0.0.0.0:8001
              --workers 3
              --timeout 120
      "
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: ${SECRET_KEY:-change-me}
      DEBUG: "False"
      TZ: Asia/Tashkent
      # ⚠️ Eslatma: settings.py da quyidagilarni unutmang:
      # ALLOWED_HOSTS = ["*", "167.86.71.176", "your.domain"]
      # CSRF_TRUSTED_ORIGINS = ["http://167.86.71.176", "https://167.86.71.176", "https://your.domain"]
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - static_data:/app/staticfiles
      - media_data:/app/media
    expose:
      - "8001"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"   # SSL bo‘lsa, bo‘lmasa olib turing
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/var/www/static:ro
      - media_data:/var/www/media:ro
      # SSL fayllaringiz bo‘lsa (Let's Encrypt):
      # - /etc/letsencrypt/live/your.domain/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      # - /etc/letsencrypt/live/your.domain/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    restart: unless-stopped
    networks:
      - app-network

volumes:
  sqlite_data:
  static_data:
  media_data:

networks:
  app-network:
    driver: bridge
