# Generated by Django 5.2.5 on 2025-08-17 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('invite_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'required_channels',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='ix_reqchan_active_prio')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('MEMBER', 'MEMBER'), ('NOT_MEMBER', 'NOT_MEMBER')], max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.requiredchannel')),
            ],
            options={
                'db_table': 'subscription_snapshots',
                'indexes': [models.Index(fields=['channel', 'status'], name='ix_snap_channel_status')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'channel'), name='uq_snapshot_user_channel')],
            },
        ),
    ]
